### ISSUE TITLE
ignoreSchematicsFromJar not working NeoForge 1.21.1

### ISSUE THREAD

**Issue by centmeteenvin** [ldtteam/Structurize#752]
### Is there an existing issue for this?

- [x] I have searched the existing issues.

### Are you using the latest Structurize Version?

- [x] I am running the latest **beta/release** version of Structurize for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [x] I checked the MineColonies/Structurize [Wiki](https://wiki.minecolonies.ldtteam.com/) or I asked on [discord](https://discord.minecolonies.com/).

### Minecraft Version

1.21

### Structurize Version

1.0.778-1.21.1

### MineColonies Version (if related bug)

1.1.984-1.21.1

### Related Mods and their Versions

NeoForge: 21.1.173

### Current Behavior

When setting the ignoreSchematicsFromJar value to true I am still able to see, access and place minecolonies defined structure packs.
```toml
#All configuration items related to the core gameplay
[gameplay]
	#Should the default schematics be ignored (from the jar)? [Default: false]
	ignoreSchematicsFromJar = true
	#Should player-made schematics be allowed? [Default: true]
	allowPlayerSchematics = true
	#Max world operations per tick (max blocks to place, remove, or replace). [Default: 1000, min: 0, max: 100000]
	# Default: 1000
	# Range: 0 ~ 100000
	maxOperationsPerTick = 1000
	#Max amount of undos saved. A higher number requires more memory. [Default: 50, min: 0, max: 250]
	# Default: 50
	# Range: 0 ~ 250
	maxCachedChanges = 50
	#Max amount of schematics to be cached on the server. [Default: 100, min: 0, max: 100000]
	# Default: 100
	# Range: 0 ~ 100000
	maxCachedSchematics = 100
	#Max amount of blocks checked by a possible worker. [Default: 1000, min: 0, max: 100000]
	# Default: 1000
	# Range: 0 ~ 100000
	maxBlocksChecked = 1000
	#How many block at most can be inside one scanned blueprint. [Default: 100000, min: 1000, max: 1000000]
	# Default: 100000
	# Range: 1000 ~ 1000000
	schematicBlockLimit = 100000
	#Currently supports 'default', 'inwardcircle', 'hilbert', 'random' and 'inwardcircleheight1' to 'inwardcircleheight4' [Default: default]
	iteratorType = "default"
```

<img width="440" alt="Image" src="https://github.com/user-attachments/assets/084e584a-4481-4eb8-97fd-158facde9414" />

### Expected Behavior

Only the player scans should be visible

### Reproduction Steps

1. Set value to true via either config screens or editing the toml file.
2. Join singleplayer world with privileges.
3. Use buildwand to open the GUI
4. Switch packs still shows all options

### Logs

https://gist.github.com/centmeteenvin/d2b284a429ed44354b962b2a863e7abc

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.
